version: '3.8'
 
services:
  service-registry:
    image: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - eureka-network

  course-service:
    image: course-service
    container_name: course-service
    environment:
      SPRING_APPLICATION_NAME: course-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SERVER_PORT: 8084
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
    ports:
      - "8084:8080"
    networks:
      - eureka-network
    depends_on:
      - eureka-server
 
  department-service:
    image: department-service
    container_name: department-service
    environment:
      SPRING_APPLICATION_NAME: department-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb1
    ports:
      - "8081:8080"
    networks:
      - eureka-network
    depends_on:
      - eureka-server
 
  enrollment-service:
    image: enrollment-service
    container_name: enrollment-service
    environment:
      SPRING_APPLICATION_NAME: enrollment-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb2
    ports:
      - "8083:8080"
    networks:
      - eureka-network
    depends_on:
      - eureka-server
 
  grading-service:
    image: grading-service
    container_name: grading-service
    environment:
      SPRING_APPLICATION_NAME: grading-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SERVER_PORT: 8086
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
    ports:
      - "8086:8080"
    networks:
      - eureka-network
    depends_on:
      - eureka-server
 
  student-service:
    image: student-service
    container_name: student-service
    environment:
      SPRING_APPLICATION_NAME: student-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:h2:mem:mydb
    ports:
      - "8082:8080"
    networks:
      - eureka-network
    depends_on:
      - eureka-server
 
networks:
  eureka-network:
    driver: bridge